version: "2"
services:
  ui:
    image: gitea/gitea:1.3.2
    volumes:
      - data:/data
    ports:
      - "3000:3000"
      - "2200:22"
    depends_on:
      - db
    networks:
      - net
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=WMH3QT6l3Qhkl1XdFGlPEIOGRBOUGxcg
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=tnaAEFCREGwnn6lzrKh8PQFhzJsDsFHz
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - net
volumes:
  db-data: {}
  data: {}
networks:
  net: {}
